// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHistory(arg1:main.HistoryItem):Promise<void>;

export function CancelDownload():Promise<void>;

export function CaptureSpDC():Promise<void>;

export function CheckSourceHealth(arg1:string):Promise<string>;

export function ClearHistory():Promise<void>;

export function ConfirmAmazonLogin():Promise<void>;

export function GetAppleMusicArtistDetail(arg1:string):Promise<string>;

export function GetAppleMusicLibrary():Promise<string>;

export function GetAppleMusicPlaylistDetail(arg1:string):Promise<string>;

export function GetArtistDiscography(arg1:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetDiscoveryData(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDiscoveryGenres(arg1:string):Promise<string>;

export function GetDownloadedMusicLibrary():Promise<string>;

export function GetDownloadedRelease(arg1:string):Promise<string>;

export function GetHistory():Promise<Array<main.HistoryItem>>;

export function GetIPodDevices():Promise<string>;

export function GetSpotifyStatus():Promise<string>;

export function GetTrackLyrics(arg1:string):Promise<string>;

export function LoginSpotify():Promise<string>;

export function LogoutSpotify():Promise<string>;

export function PauseDownload():Promise<void>;

export function PickDirectory():Promise<string>;

export function RefreshAppleMusicLibrary():Promise<string>;

export function RefreshDownloadedMusicLibrary():Promise<string>;

export function ResetAppleMusicIndex():Promise<void>;

export function ResumeDownload():Promise<void>;

export function RetryTrackDownload(arg1:string):Promise<void>;

export function RunAutoSync():Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveCoverArt(arg1:string,arg2:string):Promise<string>;

export function SearchArtists(arg1:string,arg2:string):Promise<string>;

export function SetDownloadWorkerCount(arg1:number):Promise<void>;

export function SetSpotifyCookie(arg1:string):Promise<string>;

export function SetSpotifyToken(arg1:string):Promise<string>;

export function StartAmazonBrowserLogin():Promise<void>;

export function StartAppleBrowserLogin():Promise<void>;

export function StartAppleMusicIndex():Promise<void>;

export function StartDownload(arg1:Array<string>):Promise<void>;

export function StartTidalOAuthLogin():Promise<void>;

export function ValidateTidalAuth():Promise<string>;
