// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CaptureSpDC() {
  return window['go']['main']['App']['CaptureSpDC']();
}

export function CheckSourceHealth(arg1) {
  return window['go']['main']['App']['CheckSourceHealth'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ConfirmAmazonLogin() {
  return window['go']['main']['App']['ConfirmAmazonLogin']();
}

export function GetAppleMusicArtistDetail(arg1) {
  return window['go']['main']['App']['GetAppleMusicArtistDetail'](arg1);
}

export function GetAppleMusicLibrary() {
  return window['go']['main']['App']['GetAppleMusicLibrary']();
}

export function GetAppleMusicPlaylistDetail(arg1) {
  return window['go']['main']['App']['GetAppleMusicPlaylistDetail'](arg1);
}

export function GetArtistDiscography(arg1) {
  return window['go']['main']['App']['GetArtistDiscography'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiscoveryData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDiscoveryData'](arg1, arg2, arg3);
}

export function GetDiscoveryGenres(arg1) {
  return window['go']['main']['App']['GetDiscoveryGenres'](arg1);
}

export function GetDownloadedMusicLibrary() {
  return window['go']['main']['App']['GetDownloadedMusicLibrary']();
}

export function GetDownloadedRelease(arg1) {
  return window['go']['main']['App']['GetDownloadedRelease'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetIPodDevices() {
  return window['go']['main']['App']['GetIPodDevices']();
}

export function GetSpotifyStatus() {
  return window['go']['main']['App']['GetSpotifyStatus']();
}

export function GetTrackLyrics(arg1) {
  return window['go']['main']['App']['GetTrackLyrics'](arg1);
}

export function LoginSpotify() {
  return window['go']['main']['App']['LoginSpotify']();
}

export function LogoutSpotify() {
  return window['go']['main']['App']['LogoutSpotify']();
}

export function PauseDownload() {
  return window['go']['main']['App']['PauseDownload']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RefreshAppleMusicLibrary() {
  return window['go']['main']['App']['RefreshAppleMusicLibrary']();
}

export function RefreshDownloadedMusicLibrary() {
  return window['go']['main']['App']['RefreshDownloadedMusicLibrary']();
}

export function ResetAppleMusicIndex() {
  return window['go']['main']['App']['ResetAppleMusicIndex']();
}

export function ResumeDownload() {
  return window['go']['main']['App']['ResumeDownload']();
}

export function RetryTrackDownload(arg1) {
  return window['go']['main']['App']['RetryTrackDownload'](arg1);
}

export function RunAutoSync() {
  return window['go']['main']['App']['RunAutoSync']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCoverArt(arg1, arg2) {
  return window['go']['main']['App']['SaveCoverArt'](arg1, arg2);
}

export function SearchArtists(arg1, arg2) {
  return window['go']['main']['App']['SearchArtists'](arg1, arg2);
}

export function SetDownloadWorkerCount(arg1) {
  return window['go']['main']['App']['SetDownloadWorkerCount'](arg1);
}

export function SetSpotifyCookie(arg1) {
  return window['go']['main']['App']['SetSpotifyCookie'](arg1);
}

export function SetSpotifyToken(arg1) {
  return window['go']['main']['App']['SetSpotifyToken'](arg1);
}

export function StartAmazonBrowserLogin() {
  return window['go']['main']['App']['StartAmazonBrowserLogin']();
}

export function StartAppleBrowserLogin() {
  return window['go']['main']['App']['StartAppleBrowserLogin']();
}

export function StartAppleMusicIndex() {
  return window['go']['main']['App']['StartAppleMusicIndex']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartTidalOAuthLogin() {
  return window['go']['main']['App']['StartTidalOAuthLogin']();
}

export function ValidateTidalAuth() {
  return window['go']['main']['App']['ValidateTidalAuth']();
}
