// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function AdvanceIPodCapacityUnlock(arg1) {
  return window['go']['main']['App']['AdvanceIPodCapacityUnlock'](arg1);
}

export function BrowseIPodLibrary(arg1) {
  return window['go']['main']['App']['BrowseIPodLibrary'](arg1);
}

export function CancelAutoSync() {
  return window['go']['main']['App']['CancelAutoSync']();
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelIPodOperation() {
  return window['go']['main']['App']['CancelIPodOperation']();
}

export function CancelIPodOperationByID(arg1) {
  return window['go']['main']['App']['CancelIPodOperationByID'](arg1);
}

export function CaptureSpDC() {
  return window['go']['main']['App']['CaptureSpDC']();
}

export function CheckSourceHealth(arg1) {
  return window['go']['main']['App']['CheckSourceHealth'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ConfirmAmazonLogin() {
  return window['go']['main']['App']['ConfirmAmazonLogin']();
}

export function CreateIPodBackup(arg1) {
  return window['go']['main']['App']['CreateIPodBackup'](arg1);
}

export function CreateIPodSyncPlan(arg1) {
  return window['go']['main']['App']['CreateIPodSyncPlan'](arg1);
}

export function CreateManualIPodBackup(arg1) {
  return window['go']['main']['App']['CreateManualIPodBackup'](arg1);
}

export function DeleteIPodBackup(arg1) {
  return window['go']['main']['App']['DeleteIPodBackup'](arg1);
}

export function EjectIPod(arg1) {
  return window['go']['main']['App']['EjectIPod'](arg1);
}

export function ExecuteIPodSync(arg1) {
  return window['go']['main']['App']['ExecuteIPodSync'](arg1);
}

export function ExportIPodBackup(arg1) {
  return window['go']['main']['App']['ExportIPodBackup'](arg1);
}

export function GetAppleMusicArtistDetail(arg1) {
  return window['go']['main']['App']['GetAppleMusicArtistDetail'](arg1);
}

export function GetAppleMusicLibrary() {
  return window['go']['main']['App']['GetAppleMusicLibrary']();
}

export function GetAppleMusicPlaylistDetail(arg1) {
  return window['go']['main']['App']['GetAppleMusicPlaylistDetail'](arg1);
}

export function GetArtistDiscography(arg1) {
  return window['go']['main']['App']['GetArtistDiscography'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiscoveryData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDiscoveryData'](arg1, arg2, arg3);
}

export function GetDiscoveryGenres(arg1) {
  return window['go']['main']['App']['GetDiscoveryGenres'](arg1);
}

export function GetDownloadWorkerCapacity() {
  return window['go']['main']['App']['GetDownloadWorkerCapacity']();
}

export function GetDownloadedMusicLibrary() {
  return window['go']['main']['App']['GetDownloadedMusicLibrary']();
}

export function GetDownloadedRelease(arg1) {
  return window['go']['main']['App']['GetDownloadedRelease'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetIPodBackupSnapshot(arg1) {
  return window['go']['main']['App']['GetIPodBackupSnapshot'](arg1);
}

export function GetIPodCapacityUnlockEligibility(arg1) {
  return window['go']['main']['App']['GetIPodCapacityUnlockEligibility'](arg1);
}

export function GetIPodDevices() {
  return window['go']['main']['App']['GetIPodDevices']();
}

export function GetIPodRecoveryState() {
  return window['go']['main']['App']['GetIPodRecoveryState']();
}

export function GetIPodSyncPlanDetails(arg1) {
  return window['go']['main']['App']['GetIPodSyncPlanDetails'](arg1);
}

export function GetSpotifyStatus() {
  return window['go']['main']['App']['GetSpotifyStatus']();
}

export function GetSuggestedDownloadLocation(arg1) {
  return window['go']['main']['App']['GetSuggestedDownloadLocation'](arg1);
}

export function GetThirdPartyNotices() {
  return window['go']['main']['App']['GetThirdPartyNotices']();
}

export function GetTrackLyrics(arg1) {
  return window['go']['main']['App']['GetTrackLyrics'](arg1);
}

export function InspectIPodRecoveryUSB() {
  return window['go']['main']['App']['InspectIPodRecoveryUSB']();
}

export function ListIPodBackupDevices() {
  return window['go']['main']['App']['ListIPodBackupDevices']();
}

export function ListIPodBackupSnapshots(arg1) {
  return window['go']['main']['App']['ListIPodBackupSnapshots'](arg1);
}

export function LoginSpotify() {
  return window['go']['main']['App']['LoginSpotify']();
}

export function LogoutSpotify() {
  return window['go']['main']['App']['LogoutSpotify']();
}

export function PauseDownload() {
  return window['go']['main']['App']['PauseDownload']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickIPodRecoveryFile() {
  return window['go']['main']['App']['PickIPodRecoveryFile']();
}

export function PreflightIPodMigration(arg1) {
  return window['go']['main']['App']['PreflightIPodMigration'](arg1);
}

export function PreflightIPodRestore(arg1) {
  return window['go']['main']['App']['PreflightIPodRestore'](arg1);
}

export function RefreshAppleMusicLibrary() {
  return window['go']['main']['App']['RefreshAppleMusicLibrary']();
}

export function RefreshDownloadedMusicLibrary() {
  return window['go']['main']['App']['RefreshDownloadedMusicLibrary']();
}

export function ResetAppleMusicIndex() {
  return window['go']['main']['App']['ResetAppleMusicIndex']();
}

export function ResumeDownload() {
  return window['go']['main']['App']['ResumeDownload']();
}

export function RunAutoSync() {
  return window['go']['main']['App']['RunAutoSync']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCoverArt(arg1, arg2) {
  return window['go']['main']['App']['SaveCoverArt'](arg1, arg2);
}

export function ScanIPodDevices() {
  return window['go']['main']['App']['ScanIPodDevices']();
}

export function SearchArtists(arg1, arg2) {
  return window['go']['main']['App']['SearchArtists'](arg1, arg2);
}

export function SetDownloadWorkerCount(arg1) {
  return window['go']['main']['App']['SetDownloadWorkerCount'](arg1);
}

export function SetSpotifyCookie(arg1) {
  return window['go']['main']['App']['SetSpotifyCookie'](arg1);
}

export function SetSpotifyToken(arg1) {
  return window['go']['main']['App']['SetSpotifyToken'](arg1);
}

export function StageDownloadsForIPod(arg1) {
  return window['go']['main']['App']['StageDownloadsForIPod'](arg1);
}

export function StartAmazonBrowserLogin() {
  return window['go']['main']['App']['StartAmazonBrowserLogin']();
}

export function StartAppleBrowserLogin() {
  return window['go']['main']['App']['StartAppleBrowserLogin']();
}

export function StartAppleMusicIndex() {
  return window['go']['main']['App']['StartAppleMusicIndex']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartIPodCapacityUnlock(arg1) {
  return window['go']['main']['App']['StartIPodCapacityUnlock'](arg1);
}

export function StartIPodMigration(arg1) {
  return window['go']['main']['App']['StartIPodMigration'](arg1);
}

export function StartIPodRestore(arg1) {
  return window['go']['main']['App']['StartIPodRestore'](arg1);
}

export function StartIPodWatcher() {
  return window['go']['main']['App']['StartIPodWatcher']();
}

export function StartTidalOAuthLogin() {
  return window['go']['main']['App']['StartTidalOAuthLogin']();
}

export function StopIPodWatcher() {
  return window['go']['main']['App']['StopIPodWatcher']();
}

export function UpdateIPodBackupNote(arg1) {
  return window['go']['main']['App']['UpdateIPodBackupNote'](arg1);
}

export function ValidateTidalAuth() {
  return window['go']['main']['App']['ValidateTidalAuth']();
}

export function VerifyIPodBackup(arg1) {
  return window['go']['main']['App']['VerifyIPodBackup'](arg1);
}
